package alerts

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/castiel/dns/internal/config"
)

// Alert represents a security alert generated by the DNS Attack Defender.
type Alert struct {
	Type     string    `json:"type"`
	Severity string    `json:"severity"`
	Source   string    `json:"source"`
	Domain   string    `json:"domain,omitempty"`
	Message  string    `json:"message"`
	Time     time.Time `json:"time"`
}

// Manager handles alert routing to multiple destinations:
// - JSONL log file
// - macOS unified logging (syslog)
// - macOS Notification Center (osascript)
// - Webhook (Slack/Discord)
type Manager struct {
	cfg       config.AlertsConfig
	logFile   *os.File
	mu        sync.Mutex
	alertCount map[string]int // per-type rate limiting
	lastReset time.Time
}

func NewManager(cfg config.AlertsConfig) *Manager {
	m := &Manager{
		cfg:        cfg,
		alertCount: make(map[string]int),
		lastReset:  time.Now(),
	}

	if cfg.Enabled && cfg.LogFile != "" {
		dir := filepath.Dir(cfg.LogFile)
		os.MkdirAll(dir, 0755)
		f, err := os.OpenFile(cfg.LogFile, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
		if err != nil {
			log.Printf("Failed to open alert log: %v", err)
		} else {
			m.logFile = f
		}
	}

	return m
}

func (m *Manager) Start() {
	// Periodic cleanup / log rotation could go here
}

func (m *Manager) Send(a Alert) {
	if !m.cfg.Enabled {
		return
	}

	// Check severity threshold
	if !m.meetsSeverity(a.Severity) {
		return
	}

	// Rate limit alerts per type
	if m.cfg.RateLimitAlerts {
		if m.isRateLimited(a.Type) {
			return
		}
	}

	// Log to JSONL file
	if m.logFile != nil {
		m.mu.Lock()
		data, _ := json.Marshal(a)
		m.logFile.Write(data)
		m.logFile.Write([]byte("\n"))
		m.mu.Unlock()
	}

	// macOS unified logging (syslog)
	if m.cfg.SyslogEnabled {
		log.Printf("[%s] %s: %s (source=%s domain=%s)",
			a.Severity, a.Type, a.Message, a.Source, a.Domain)
	}

	// macOS Notification Center
	if m.cfg.DesktopNotification && (a.Severity == "critical" || a.Severity == "warn") {
		m.sendDesktopNotification(a)
	}

	// Webhook
	if m.cfg.WebhookEnabled && m.cfg.WebhookURL != "" {
		go m.sendWebhook(a)
	}
}

func (m *Manager) meetsSeverity(severity string) bool {
	levels := map[string]int{
		"debug":    0,
		"info":     1,
		"warn":     2,
		"critical": 3,
	}
	minLevel, ok := levels[m.cfg.MinSeverity]
	if !ok {
		minLevel = 2
	}
	alertLevel, ok := levels[severity]
	if !ok {
		return false
	}
	return alertLevel >= minLevel
}

func (m *Manager) isRateLimited(alertType string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Reset counters every minute
	if time.Since(m.lastReset) > time.Minute {
		m.alertCount = make(map[string]int)
		m.lastReset = time.Now()
	}

	m.alertCount[alertType]++
	return m.alertCount[alertType] > 10 // Max 10 alerts per type per minute
}

func (m *Manager) sendDesktopNotification(a Alert) {
	title := platformNotificationTitle(a.Severity)
	body := a.Message
	if a.Domain != "" {
		body = fmt.Sprintf("%s — Domain: %s", a.Message, a.Domain)
	}
	log.Printf("Desktop notification: %s — %s", title, body)
	sendPlatformNotification(title, body, a.Severity)
}

func (m *Manager) sendWebhook(a Alert) {
	// In production, use net/http to POST JSON to webhook URL
	data, _ := json.Marshal(a)
	log.Printf("Webhook alert: %s", string(data))
}

func (m *Manager) Close() {
	if m.logFile != nil {
		m.logFile.Close()
	}
}
